### ISSUE TITLE
Copy & Paste of text rendered via decorator

### ISSUE THREAD

**Issue by beny64** [thibaudcolas/draftjs-conductor#12]
**I am not sure if I do something wrong or it is a bug**

Here is complete repo with a minimalist example and the problem description: https://github.com/beny64/draft-copy-paste

In short: I use custom entities rendered via decorators. `handleDraftEditorPastedText` does great job for getting a new record in ContentState.entityMap for the copied entity when the whole entity is selected (C&P within Draft Editor).

But if I select only part of text inside the rendered entity, there are two results of C&P (according to the selected text):
1. nothing is copied
2. the whole entity is copied 

Any advice? Thanks

**Comment by thibaudcolas** [comment]
Hey @beny64, thank you for taking the time to put a detailed example together!

I'm on holidays right now so haven't had time to fully investigate, but at first glance this seems to be a similar issue to https://github.com/facebook/draft-js/issues/1641. This library uses [`getFragmentFromSelection`](https://github.com/thibaudcolas/draftjs-conductor/blob/d0c8d8a7b3729d5f843da0b692707a91eb210da7/src/lib/api/copypaste.js#L24-L26) from Draft.js to determine what content is selected on copy, I imagine it's at this stage that there might be an issue in determining what is included in the selection.

I'll get back to this after holidays and see whether something can be done about the current behavior.

**Comment by thibaudcolas** [comment]
Hey @beny64, I finally started looking into this – hoping to get a fix out this week.

I've been trying to reproduce this locally and seem to be getting three different results:

- Copying only some part of the text from the decorator, then nothing is pasted
- Copying the whole text of the decorator, a single space character is pasted (" ")
- Copying the whole decorator (say from the block before to the block after), then pasting does what I would expect.

I think this matches what you described in https://github.com/beny64/draft-copy-paste, except maybe for the "copying the whole text" part, which for you pasted the whole entity. This might just be due to my setup to reproduce this.

For solutions, I think;

1. Copying only some text should paste the corresponding text, as if the copy/paste had no special behavior with regards to entities
2. Copying the whole text – I'm not super clear on how that should work, will need to explore more.
3. Copying the whole decorator from preceding to following block should work the same as now.

The first point sounds doable, the second I'm not sure yet. An alternative solution would be to recommend using `user-select: none;` on all text rendered by decorators to completely prevent it from being copied.

Do you have any thoughts on this before I spend more time?

**Comment by beny64** [comment]
Hi @thibaudcolas, thanks for your effort. I had to redesign my editor (for other reasons) for using nested editors (I know, it is not recommended, but we believe we need them, despite of their complexity), so this issue is not relevant for me now (but it can reappear).
So if I am the only one, save your time.

To your suggestion - points 1 and 3 are clear. I understand your doubt about point 2. For example (un)ordered list item:

- select the whole line by mouse move, paste it somewhere. Only the selected text is pasted.
- select the whole line by triple click, paste it somewhere. A new list with one bullet is created.

Similar results can be done by keyboard.
Well, we know what is the difference, but from user's point of view it could be confusing. They always see a single line selection. I would prefer the same behavior as when only some text is selected, not to copy the whole entity.

**Comment by thibaudcolas** [comment]
I think I managed to fix this as part of #12. Now, the copy-paste handling will check whether the selection is within a decorator that would have this issue – and if so, will leave it up to the browser to determine what to copy-paste. The issue was that Draft.js didn't handle selections for content that's not editable.

**Comment by thibaudcolas** [comment]
:tada: This issue is fixed in v0.4.4, available on npm: [draftjs-conductor@0.4.4](https://www.npmjs.com/package/draftjs-conductor).

<p align="right">
Generated by :package::rocket: <a href="https://github.com/semantic-release/semantic-release">semantic-release</a>
</p>
