### ISSUE TITLE
Copy doesn't work if ReadOnly is on

### ISSUE THREAD

**Issue by Omhet** [thibaudcolas/draftjs-conductor#14]
When I copy some content from an editor with ReadOnly set to true and try to paste it in an editor with ReadOnly set to false I get just plain text.

**Comment by thibaudcolas** [comment]
Hey @Omhet, thanks for the report. I've actually never used Draft.js in read-only mode, and don't have any project implementing it. Could you provide a demo so I can have a look?

**Comment by Omhet** [comment]
Hey @thibaudcolas, you know, It's something strange going on. I've made a simple demo and it just works.
But in my work in a big project it doesn't work. There are different instances of DraftJS with different versions with content loaded from a server, and some versions can also be ReadOnly.
If I can reproduce this bug in a simple demo I will let you know

**Comment by thibaudcolas** [comment]
Good to know 👌 I'll leave this open for now, and attempt to repro it myself, see what happens.

**Comment by Omhet** [comment]
Well, now I find it. It doesn't work only with custom styles.
Here's a link to the demo: https://codesandbox.io/s/l7nm98px6z

**Comment by thibaudcolas** [comment]
Great, well now it's pretty clear there is a problem!

I've looked at the demo and I think I know where this is coming from. In the code that serialises the selected content, https://github.com/thibaudcolas/draftjs-conductor/blob/5f7ed70231dbeda70c217301409bfb6872d0b988/src/lib/api/copypaste.js#L32-L35

`getFragmentFromSelection` returns `null` if the selection is within a read-only editor. This is because the Draft.js selection state doesn't reflect selections happening in read-only mode (as far as I can see). For Draft.js, the selection is collapsed, thus there is no fragment to copy. Implementation on the Draft.js side: https://github.com/facebook/draft-js/blob/585af35c3a8c31fefb64bc884d4001faa96544d3/src/component/handlers/edit/getFragmentFromSelection.js#L19-L24

To fix this, I think it might be possible to use the `getContentStateFragment` internal API of Draft.js instead of `getFragmentFromSelection`, providing it with a purpose-built selection state that would reflect the native selection's location. The hard part would be in creating a Draft.js SelectionState from the DOM’s `window.getSelection()`, but it seems that Draft.js has a `getDraftEditorSelection` internal API that implements this already: https://github.com/facebook/draft-js/blob/585af35c3a8c31fefb64bc884d4001faa96544d3/src/component/selection/getDraftEditorSelection.js.

I don't have time to attempt to fix this right now, but if you want to go for it I'm happy to help. The first step would probably be to hack together a combination of `getContentStateFragment` and `getDraftEditorSelection` to see if that approach works in read-only mode, then determine whether to use this or the current implementation in the different cases.

**Comment by Omhet** [comment]
It sounds reasonable. I'll try to work it over in my spare time

**Comment by Omhet** [comment]
Well, I finally has tried to work it out the way you proposed. Using `getContentStateFragment `and `getDraftEditorSelection ` actually works fine! Although one of your tests failed and I don't know what the problem

**Comment by Omhet** [comment]
![Screenshot](https://user-images.githubusercontent.com/33632745/55941596-2b48ba80-5c4b-11e9-8f25-3ae8cdf6bcff.png)

**Comment by Omhet** [comment]
![Untitled](https://user-images.githubusercontent.com/33632745/55941848-bfb31d00-5c4b-11e9-9573-6c181d9b3956.png)

**Comment by Omhet** [comment]
So I see that done callback was not called in that test and time has run out, but I don't get why

**Comment by thibaudcolas** [comment]
Ah sweet! Could you make a pull request with those changes so I can try out the new implementation?

For the test failure, I wouldn't be surprised if it was the test’s implementation/assumptions that were wrong and not an issue with the changes.

This code looks a bit funny: https://github.com/thibaudcolas/draftjs-conductor/blob/5f7ed70231dbeda70c217301409bfb6872d0b988/src/lib/api/copypaste.test.js#L143-L153

I'm not sure why `done()` isn't called for text-only copy-paste. And then the selection mocking above it might be wrong as well, for the purpose of the new implementation.

Anyway, if you can look into the test failure that would be ideal, but if not I'll pick it up from your PR.

**Comment by Omhet** [comment]
Ah, ok, will make a pr now. Not sure if I can handle the failure myself, actually I have little experience with tests :disappointed:

**Comment by Omhet** [comment]
Please, let me know, if you publish these changes

**Comment by thibaudcolas** [comment]
:tada: This issue is fixed in v0.4.3, available on npm: [draftjs-conductor@0.4.3](https://www.npmjs.com/package/draftjs-conductor).

<p align="right">
Generated by :package::rocket: <a href="https://github.com/semantic-release/semantic-release">semantic-release</a>
</p>
